spring:
  datasource:
    url: "jdbc:mysql://dummy-prod-db:0000/mailtemplater"
    username: "root"
    driver-class-name: "com.mysql.jdbc.Driver"

web:
  cors:
    allowedOrigins: http://dummy-prod-db:0000
