spring:
  datasource:
    url: "jdbc:mysql://dummy-prod-db:0000/mailtemplater"
    username: "root"
    driver-class-name: "com.mysql.jdbc.Driver"

web:
  cors:
    allowedOrigins: http://dummy-fe-admin:4200, http://dummy-fe-client:5200
    adminFeApp: http://dummy-fe-admin:4200
    clientFeApp: http://dummy-fe-client:5200
