spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mailtemplater?createDatabaseIfNotExist=true"
    username: ${db_username:EmailTemplaterUser}
    password: ${db_password:}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
web:
  cors:
    allowedOrigins: http://localhost:4200, http://localhost:5200
    adminFeApp: http://localhost:4200
    clientFeApp: http://localhost:5200

local:
  sender:
    username: test # Change for local usage only - don't commit.
    password: test # Change for local usage only - don't commit.
