spring:
  profiles:
    active: dev

server:
  error:
    include-message: always
    include-binding-errors: always

email:
  smtp:
    defaultServerName: gmail
    servers:
      - host: smtp.gmail.com
        port: 587
        auth: true
        starttls:
          enable: true
        timeout: 30000
        connectiontimeout: 30000
        name: gmail
      - host: email.uni-sofia.bg
        port: 465
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true
        timeout: 30000
        connectiontimeout: 30000
        name: unisofia
      - host: smtp.abv.bg
        port: 465
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true
        timeout: 30000
        connectiontimeout: 30000
        name: abv

email-templates:
  placeholder-prefix: "%("
  placeholder-suffix: ")"
  message-max-length: 2048 # Database based constraint

