spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mailtemplater"
    username: "root"
    driver-class-name: "com.mysql.jdbc.Driver"

server:
  error:
    include-message: always
    include-binding-errors: always

# Gmail SMTP
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true

# FMI SMTP
#mail:
#  smtp:
#    host: email.uni-sofia.bg
#    port: 465
#    auth: true
#    starttls:
#      enable: true

email-templates:
  placeholder-prefix: "%("
  placeholder-suffix: ")"
