spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mailtemplater"
    username: ${db_username:rootfmi}
    password: ${db_username:22rootfmi23}
    driver-class-name: "com.mysql.jdbc.Driver"

web:
  cors:
    allowedOrigins: http://localhost:4200, http://localhost:5200
    adminFeApp: http://localhost:4200
    clientFeApp: http://localhost:5200
