spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mailtemplater"
    username: ${db_username:rootfmi}
    password: ${db_password:22rootfmi23}
    driver-class-name: "com.mysql.jdbc.Driver"

web:
  cors:
    allowedOrigins: http://localhost:4200, http://localhost:5200
    adminFeApp: http://localhost:4200
    clientFeApp: http://localhost:5200

local:
  sender:
    username: test # Change for local usage only - don't commit.
    password: test # Change for local usage only - don't commit.
